services:
    agit.intl.locale:
        class: Agit\IntlBundle\Service\LocaleService
        arguments: [ "@?agit.intl.localeconfig", "%agit.intl.locales%", "%kernel.root_dir%/Resources/translations", "agit" ]

    # (Optional) Twig extension for template text block translations
    agit.intl.twig.translation:
        class: Agit\IntlBundle\Service\TranslationExtension
        arguments: [ "@agit.intl.locale" ]
        tags: [{ name: twig.extension }]

    # checks if a bundle has Twig templates, and prepares them for extraction
    agit.intl.bundle.twig.collect:
        class: Agit\IntlBundle\EventListener\TranslationTwigListener
        arguments: [ @agit.common.filecollector, @twig ]
        tags: [{ name: kernel.event_listener, event: agit.intl.files.register, method: onRegistration }]
